//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bank.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Transaction()
        {
            this.CashTransactions = new HashSet<CashTransactions>();
        }
    
        public int TransactionId { get; set; }
        public int UserId { get; set; }
        public Nullable<int> AccountId { get; set; }
        public decimal TransactionAmount { get; set; }
        public decimal Deposit { get; set; }
        public decimal Withdrawl { get; set; }
        public string TransactionType { get; set; }
        public System.DateTime TransactionDate { get; set; }
    
        public virtual Account Account { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CashTransactions> CashTransactions { get; set; }
        public virtual User User { get; set; }
    }
}
